# Generated by Django 5.2 on 2025-05-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[(1, 'mobile'), (2, 'shoes'), (3, 'cloths')], verbose_name='category')),
                ('pdetails', models.CharField(max_length=100, verbose_name='product details')),
                ('is_active', models.BooleanField(default=True)),
                ('pimage', models.ImageField(upload_to='Images/')),
            ],
        ),
    ]
