# Generated by Django 5.2 on 2025-05-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(1, 'mobile'), (2, 'shoes'), (3, 'cloths')], max_length=20, verbose_name='category'),
        ),
    ]
