# Generated by Django 5.2 on 2025-05-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'mobile'), (2, 'shoes'), (3, 'cloths')], max_length=20, verbose_name='category'),
        ),
    ]
